name = "Home computer"
afk_interval = 10

[[activity]]
    name = "coding"

    # 1 = Productive, -1 = Leisure, 0 = Neutral
    productivity = 1

    [[activity.rule]]
        for_name = ["code-oss"]
        title_contains_any = ["trackr", "frontend"]

    [[activity.rule]]
        # Grabbing by app name
        for_name = ["Navigator", "Google-Chrome"]

        # Providing multiple criteria is equivalent to "OR" operation
        title_contains_any = ["trackr"]
        # title_contains_all = ["github"]
        # title_is = ""
        # title_ends_with = ""
        # title_starts_with = ""


